### ISSUE TITLE
Sobre TwCLI

### ISSUE THREAD

**Issue by Makova** [elecciones-ugr/scraper#4]
Pregunto ¿hubiese quedado mejor en otro repo, como el de la app, o scraper?. Que por cierto ¡¡Mola!! 
En el TATGranada me enseño Pablo a instalarlo y utilizarlo por la terminal.

**Comment by JJ** [comment]
es posible, pero están relacionados, porque el twitter se ejecuta desde el
de perl.

2015-05-26 13:13 GMT+02:00 Manu <notifications@github.com>:

> Pregunto ¿hubiese quedado mejor en otro repo, como el de la app, o
> scraper?.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/scraper/issues/4>.
>



-- 
JJ

**Comment by Makova** [comment]
Ok, cierro este issue.
